import express from "express";
import swaggerUi from "swagger-ui-express";
import { RegisterRoutes } from "./generated/routes";
import { config } from "./config/config";
import { serviceBusIntegration } from "./integrations/ServiceBusClient";
import swaggerJson from "./generated/swagger.json";

import { collectDefaultMetrics, register } from "prom-client";

// Start collecting default metrics
collectDefaultMetrics();

const app = express();

app.use(express.json());

// Load swagger output (generated by tsoa)
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerJson));

app.get("/health", (req: express.Request, res: express.Response) => {
    res.status(200).json({ status: "OK", timestamp: new Date().toISOString() });
});

app.get("/metrics", async (req: express.Request, res: express.Response) => {
    try {
        res.set("Content-Type", register.contentType);
        res.end(await register.metrics());
    } catch (ex) {
        res.status(500).end(ex);
    }
});

// Register TSOA generated routes
RegisterRoutes(app);

import { ValidateError } from "tsoa";

app.use(function errorHandler(
    err: unknown,
    req: express.Request,
    res: express.Response,
    next: express.NextFunction,
): express.Response | void {
    if (err instanceof ValidateError) {
        console.warn(`Caught Validation Error for ${req.path}:`, err.fields);
        return res.status(400).json({
            message: "Validation Failed",
            details: err?.fields,
        });
    }
    if (err instanceof Error) {
        return res.status(500).json({
            message: "Internal Server Error",
        });
    }

    next();
});

const server = app.listen(config.port, () => {
    console.log(`Server running on port ${config.port}`);
    console.log(`API URL: http://localhost:${config.port}/api/warranty-claim`);
    console.log(`Swagger UI: http://localhost:${config.port}/api-docs`);
});

server.on("error", (error) => {
    console.error("Error starting server:", error.message);
});

// Graceful shutdown
process.on("SIGTERM", async () => {
    console.log("SIGTERM signal received: closing HTTP server");
    await serviceBusIntegration.close();
    server.close(() => {
        console.log("HTTP server closed");
    });
});
