import 'dotenv/config';
import express from 'express';
import { sendMessage } from './serviceBusClient';
import swaggerUi from 'swagger-ui-express';
import swaggerDocs from './generated/swagger-output.json';
import { createWarranty } from './db';

const app = express();
const port = process.env.PORT || 3000;

app.use(express.json());

// Load swagger output (generated by swagger-autogen)
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocs));

app.get('/health', (req: express.Request, res: express.Response) => {
    res.status(200).json({ status: 'OK', timestamp: new Date().toISOString() });
});

interface WarrantyClaimRequest {
    orderID: number;
    userID: number;
}

app.put('/api/warranty-claim', async (req: express.Request<{}, {}, WarrantyClaimRequest>, res: express.Response) => {
    const { orderID, userID } = req.body;

    // Validate that both parameters are present and are integers
    if (!Number.isInteger(orderID)) {
        res.status(400).json({ error: 'orderID must be an integer' });
        return;
    }

    console.log(`Received warranty claim for Order: ${orderID}, User: ${userID}`);

    try {
        await sendMessage({ orderID, userID });
        res.status(200).json({
            message: 'Warranty claim processed successfully',
            data: { orderID, userID }
        });
        createWarranty(orderID, 'Registered');
    } catch (error: any) {
        console.error('Error processing warranty claim:', error);
        if (error.message === "Timeout waiting for warranty confirmation") {
            res.status(504).json({ error: 'Gateway Timeout: No confirmation received' });
        } else {
            res.status(500).json({ error: 'Internal Server Error' });
        }
    }
});

app.listen(port, () => {
    console.log(`Server running on port ${port}`);
    console.log(`API URL: http://localhost:${port}/api/warranty-claim`);
    console.log(`Swagger UI: http://localhost:${port}/api-docs`);
}).on('error', (error) => {
    console.error('Error starting server:', error.message);
});
